////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the XeNeu project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
//#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "XeNeuMigdalMessenger.hh"
#include "XeNeuMigdalDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
XeNeuMigdalMessenger::XeNeuMigdalMessenger( XeNeuMigdalDetector *Det )
  : XeNeudetector( Det )
{
  //  Set up the directory
  XeNeuDir = new G4UIdirectory( "/XeNeuMigdal/" );
  XeNeuDir->SetGuidance( "All XeNeuMigdal project commands are contained under /XeNeuMigdal/" );

  XeNeuMigdal_DDShieldingCommand = new G4UIcmdWithABool("/XeNeuMigdal/ddShieldingOn", this);
  XeNeuMigdal_DDShieldingCommand->SetGuidance("Turns the dd shielding geometry on or off.");
  XeNeuMigdal_DDShieldingCommand->SetGuidance(" The default choice is false." );
  XeNeuMigdal_DDShieldingCommand->AvailableForStates( G4State_PreInit, G4State_Idle );

  XeNeuMigdal_DTShieldingCommand = new G4UIcmdWithABool("/XeNeuMigdal/dtShieldingOn", this);
  XeNeuMigdal_DTShieldingCommand->SetGuidance("Turns the dt shielding geometry on or off.");
  XeNeuMigdal_DTShieldingCommand->SetGuidance(" The default choice is false." );
  XeNeuMigdal_DTShieldingCommand->AvailableForStates( G4State_PreInit, G4State_Idle ); 
}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
XeNeuMigdalMessenger::~XeNeuMigdalMessenger()
{
  //delete everything that you declared with new
  delete XeNeuDir;
  delete XeNeuMigdal_DDShieldingCommand;
  delete XeNeuMigdal_DTShieldingCommand;
}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void XeNeuMigdalMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  
   if( command == XeNeuMigdal_DDShieldingCommand ){
      XeNeudetector->SetXeNeuMigdal_DDShielding( XeNeuMigdal_DDShieldingCommand->GetNewBoolValue(newValue) );
   }

   if( command == XeNeuMigdal_DTShieldingCommand ){
      XeNeudetector->SetXeNeuMigdal_DTShielding( XeNeuMigdal_DTShieldingCommand->GetNewBoolValue(newValue) ); 
   }
}

