////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define XeNeu geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef XeNeuMigdalDetector_HH
#define XeNeuMigdalDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
//#include "XeNeuMigdalDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class XeNeuMigdalMessenger;
class XeNeuMigdalMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class XeNeuMigdalDetector : public BaccDetector
{
public:
  XeNeuMigdalDetector( G4String, G4String );
  ~XeNeuMigdalDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();
  void SetXeNeuMigdal_DDShielding( G4bool val ) { ddShieldingOn = val; }
  void SetXeNeuMigdal_DTShielding( G4bool val ) { dtShieldingOn = val; } 
  //  Registration methods below
  //
  G4bool GetXeNeuMigdal_DDShielding() { return ddShieldingOn; }
  G4bool GetXeNeuMigdal_DTShielding() { return dtShieldingOn; }  
private:
  XeNeuMigdalMessenger *XeNeumessenger;
  XeNeuMigdalMaterials *XeNeumaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
  G4bool ddShieldingOn = false;
  G4bool dtShieldingOn = false;
};

#endif
