////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the XeNeu project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef XeNeuMigdalMessenger_HH
#define XeNeuMigdalMessenger_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"
#include "G4UImessenger.hh"

//
//      Class forwarding
//
class G4UIdirectory;
// Uncomment the class that you will need
//class G4UicmdWithAnInteger;
//class G4UicmdWithoutParameter;
//class G4UicmdWithAString;
class G4UIcmdWithABool;
//class G4UIcmdWithADoubleAndUnit;
//class G4UicmdWithADouble;

class XeNeuMigdalDetector;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class XeNeuMigdalMessenger : public G4UImessenger
{
public:
  XeNeuMigdalMessenger( XeNeuMigdalDetector* );
  ~XeNeuMigdalMessenger();
  
  void SetNewValue( G4UIcommand*, G4String );
  
private:
  XeNeuMigdalDetector *XeNeudetector;
  
  //      The directory
  G4UIdirectory *XeNeuDir;

  // Declare the UI commands below
  G4UIcmdWithABool * XeNeuMigdal_DDShieldingCommand;
  G4UIcmdWithABool * XeNeuMigdal_DTShieldingCommand;  
};

#endif
